server:
  port: 8092


spring:
  application:
    name: admin-service

eureka:
  instance:
    instance-id: admin-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

