server:
  port: 8091


spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: user-service

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

